In [1]:
import pandas as pd
import numpy as ny
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset=dataset.astype(int)

In [5]:
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [8]:
dependent=dataset[['charges']]
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent, dependent,test_size=0.30, random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [11]:
x_train

array([[-1.5330973 , -0.36100765, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.278355  , -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.51612426,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.84052963, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.75787698, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.95941426, -0.06746417, -0.97676557, -0.50466988]])

In [12]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid= {'kernel': ['rbf', 'poly', 'sigmoid','linear'], 'c': [10,100,100,2000,3000], 'gamma': ['auto', 'scale']}
grid= GridSearchCV(SVR(),param_grid, refit= True, verbose=3, n_jobs=-1 )

In [14]:
grid.fit(x_train, y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

ValueError: Invalid parameter 'c' for estimator SVR(). Valid parameters are: ['C', 'cache_size', 'coef0', 'degree', 'epsilon', 'gamma', 'kernel', 'max_iter', 'shrinking', 'tol', 'verbose'].

In [ ]:
from sklearn.svm import SVR
regressor=SVR(kernel="rbf", C=5000)
regressor.fit(x_train,y_train)

In [ ]:
regressor.intercept_

In [ ]:
regressor.n_support_

In [ ]:
y_pred=regressor.predict(x_test)

In [ ]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [ ]:
r_score

In [ ]:
import pickle
filename="finalized_model_Support_Vector_Machine.sav"
pickle.dump(regressor,open(filename,"wb"))

In [ ]:
loaded_model=pickle.load(open("finalized_model_Support_Vector_Machine.sav",'rb'))

In [ ]:
result=loaded_model.predict([[42, 28, 2, 1, 0]])

In [ ]:
result