In [1]:
!pip install xgboost

Requirement already satisfied: xgboost in c:\users\evangeline\anaconda3\lib\site-packages (2.0.3)
Requirement already satisfied: numpy in c:\users\evangeline\anaconda3\lib\site-packages (from xgboost) (1.24.3)
Requirement already satisfied: scipy in c:\users\evangeline\anaconda3\lib\site-packages (from xgboost) (1.11.1)

In [4]:
import pandas as pd
import xgboost as xgb

In [5]:
dataset=pd.read_csv("insurance_pre.csv")

In [6]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [7]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset=dataset.astype(int)

In [8]:
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [9]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [10]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [11]:
dependent=dataset[['charges']]
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent, dependent,test_size=0.30, random_state=0)

In [16]:
from xgboost import XGBRegressor

In [17]:
xg_regressor=XGBRegressor()

In [19]:
xg_regressor.fit(x_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [21]:
y_pred=xg_regressor.predict(x_test)

In [22]:
y_pred

array([ 8735.881  ,  8936.084  , 45787.27   , 12777.143  ,  9174.248  ,
        8322.359  ,  1470.621  ,  9575.015  ,  5925.397  ,  7341.353  ,
        5294.9346 , 26758.738  , 11853.456  ,  8609.975  , 20326.932  ,
       12377.765  , 12606.101  ,  3457.2676 ,  6963.8765 , 33181.32   ,
       21549.016  , 15716.027  ,  9593.307  , 25251.076  ,  5169.383  ,
        6947.713  , 11428.84   ,  8071.4717 ,  3223.4717 , 11369.875  ,
        8872.406  , 49522.71   , 16726.521  , 12105.834  , 19699.975  ,
        3542.482  ,  8216.974  , 34836.19   , 39482.96   ,  1603.1473 ,
        7875.6074 ,  4759.342  , 22051.227  , 49742.     , 35881.914  ,
        5084.6523 , 18011.684  ,  7636.377  ,  3627.648  , 11658.575  ,
        2154.7585 ,  4435.351  , 25250.463  , 56568.5    , 12849.928  ,
        6408.4976 ,  3217.3892 , 11752.579  ,  9914.402  , 16467.75   ,
        1977.9147 , 43620.793  , 21075.137  , 24032.52   , 16543.586  ,
       10054.889  , 33439.1    , 38193.742  ,  3317.413  , 11420.965  ,
       17168.842  ,  8182.257  , 17266.453  , 14025.036  , 13012.282  ,
       16658.951  , 11885.027  , 13427.878  , 19270.045  , 52838.723  ,
       11585.776  , 57078.79   ,  3798.7705 , 11081.756  , 39023.004  ,
       20642.3    ,  4736.2993 ,  2719.2886 , 10632.55   , 37739.01   ,
        5431.835  , 11504.744  ,  2538.2244 , 19802.42   ,  7692.3174 ,
        3601.4614 , 41293.527  , 44151.484  ,  5535.453  , 10431.381  ,
        2639.5261 ,  5988.9214 ,  7086.4487 , 38858.543  , 27469.887  ,
        5841.7676 , 10584.096  ,  1798.3312 , 12109.286  , 45764.113  ,
       11608.346  ,  9814.889  ,  8672.503  , 34623.617  , 48889.41   ,
        7241.6245 ,  2513.892  , 11752.579  , 25052.713  ,  9123.024  ,
       46130.254  , 11994.996  , 14821.992  , 10436.834  ,  9579.961  ,
        1821.4524 , 24008.412  , 27346.756  , 48119.11   ,  1879.5181 ,
       22899.055  ,   562.95575,  5332.853  ,  6748.85   , 46671.266  ,
       38155.117  , 23622.87   , 24252.701  , 22520.686  ,  7210.6216 ,
        2377.595  , 11046.586  , 12901.439  , 12081.827  ,  9075.637  ,
       14433.073  , 27613.117  , 17680.104  ,  1610.793  , 12467.539  ,
        6517.427  , 36138.242  ,  8336.698  ,  8646.106  ,  7463.771  ,
        6994.3965 ,  4656.371  ,  6803.27   , 12377.765  , 11361.663  ,
        9673.484  , 13294.111  , 13672.047  ,  8353.793  , 10158.765  ,
        9258.089  , 16944.75   ,  6481.438  ,  4505.178  ,  2782.6282 ,
        8029.2344 ,  4695.66   ,  9786.101  ,  2337.3997 , 13730.278  ,
       10665.168  ,  3501.7478 ,  6632.915  , 25231.836  ,  1279.5172 ,
       16878.086  ,  5849.9023 , 12074.233  ,  8646.055  , 10023.887  ,
       27901.838  ,  4799.772  ,  3376.3687 , 13988.161  , 10848.029  ,
       41115.066  ,  6290.8066 ,  5738.9697 , 27071.89   ,  3399.2708 ,
        4807.1855 ,  7922.058  ,  4404.418  ,  9089.138  ,  4245.818  ,
       12955.034  , 45850.305  , 15676.7    , 19058.531  , 14211.369  ,
       40264.906  ,  2891.8816 ,  8835.071  ,  8783.695  ,  2641.4631 ,
        9034.314  , 14340.252  ,  5902.215  ,  3329.763  ,  6718.3286 ,
       17332.26   ,  6828.9824 , 11241.693  , 13498.573  ,  7563.4604 ,
       16556.092  ,  7437.068  ,  8312.515  ,  8575.637  , 12275.384  ,
       17519.973  , 23577.564  , 12832.932  ,  5966.457  ,  1471.3179 ,
        9733.464  ,  7064.993  , 17969.986  ,  7326.4653 ,  5628.86   ,
        6337.7935 , 11702.813  , 34513.586  ,  6007.1885 , 11961.668  ,
        5641.3677 , 47614.977  ,  8591.54   ,  5822.1436 ,  8610.511  ,
       10418.186  ,  4011.024  ,  7554.1685 ,  5392.106  ,  6358.654  ,
       20195.703  , 43527.668  ,  4690.8945 ,  4918.18   ,  7439.7173 ,
        1581.3428 ,  6995.5884 ,  2421.3923 ,  8701.525  , 11429.5    ,
        7899.819  , 24814.709  , 45197.914  , 13507.951  ,  6718.3286 ,
       11208.939  , 45153.207  , 13446.923  , 41144.457  ,   350.8274 ,
       37122.79   ,  5433.925  , 12772.427  ,  4643.5347 , 40403.504  ,
        4941.8447 ,  9964.045  ,  9163.499  ,  3603.0112 , 19379.26   ,
       12143.666  ,  9214.839  , 14647.369  , 11106.686  ,  7434.5947 ,
        5017.9604 , 10155.092  , 20180.127  ,  1493.9672 ,  1428.3639 ,
        2082.8706 , 52933.52   , 11090.444  ,  3628.2534 , 17062.998  ,
       21823.094  , 33947.516  ,  8016.551  ,  4770.807  ,  8353.695  ,
        2615.1423 ,  4266.7163 , 15323.284  , 20011.455  , 13331.837  ,
        1645.3855 ,  3321.0674 , 19045.172  ,  8726.529  , 16118.584  ,
       20259.248  ,  9767.903  , 18593.113  ,  3358.5503 ,  7440.4976 ,
        7692.3174 , 23274.48   ,  2080.6729 ,  7765.388  , 48788.52   ,
        2911.1226 ,  5390.407  ,  2010.0499 , 13126.208  ,  3421.6885 ,
       12030.984  , 45082.88   , 17499.53   ,  8713.989  , 45569.754  ,
       20637.938  , 14785.15   ,  8213.837  ,  5175.802  , 27431.008  ,
        4069.5923 , 13915.631  ,  1127.5646 , 16642.076  ,  3217.247  ,
       24529.744  , 21538.549  , 17332.26   , 44990.332  ,  7488.309  ,
        4890.898  , 27133.732  ,  2615.1423 , 10122.272  ,  2872.5283 ,
       15615.966  ,  3879.9019 ,  7428.537  ,  9481.75   , 44948.562  ,
        6704.572  , 37564.492  , 38731.74   ,  6007.1885 , 11035.124  ,
        1320.2281 , 12513.3125 ,  4108.4565 , 11825.49   , 47502.734  ,
       10210.755  ,  1188.2648 , 12321.939  ,  2492.262  , 11708.116  ,
       13501.916  ,  1335.4863 ,  3893.5583 , 36635.55   ,  6438.683  ,
        2142.142  , 43297.19   , 13695.884  , 47009.95   , 10221.426  ,
        5360.5205 ,  1200.1838 ,  2093.547  , 24610.885  ,  5049.6577 ,
        1902.0765 ,  9461.312  ,  5890.6655 ,  6398.29   ,  6290.8066 ,
       10002.698  , 39542.477  ,  7418.7407 , 16545.334  ,  7627.5205 ,
       18253.46   , 10485.746  ,  4336.9937 , 16861.559  , 10554.938  ,
       15923.067  , 18248.764  ], dtype=float32)

In [23]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [24]:
r_score

0.8073014454512222